#code/Dockerfile
FROM python:3.14-bookworm

# Copy our code to the firmware directory
WORKDIR /firmware
COPY ./requirements_new.txt /firmware/requirements.txt
COPY dependencies /firmware/dependencies

# Update apt sources
RUN apt-get update

# Update pip
RUN pip install --upgrade pip --break-system-packages

# Install apt dependencies
RUN apt-get -y install portaudio19-dev
RUN apt-get -y install python3-pyaudio
RUN apt-get -y install ffmpeg
RUN apt-get -y install alsa-utils
RUN apt-get -y install libbluetooth-dev
RUN apt-get -y install network-manager
RUN apt-get -y install wireless-tools
RUN apt-get -y install swig

# Download, compile, and install the lgpio C library from source
RUN wget https://github.com/joan2937/lg/archive/master.zip \
    && unzip master.zip \
    && cd lg-master \
    && make \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf master.zip lg-master

# Install python dependenices
RUN pip install -r requirements.txt --no-cache-dir --break-system-packages
RUN pip install --no-cache-dir rpi-lgpio 
# Patch smbus2 buffer overflow bug for Python 3.14 on 64-bit systems
RUN sed -i 's/f = c_uint32()/import ctypes; f = ctypes.c_ulong()/g' /usr/local/lib/python3.14/site-packages/smbus2/smbus2.py
# Compile whisper
COPY whisper.cpp /firmware/whisper.cpp
WORKDIR /firmware/whisper.cpp
RUN make
RUN ./models/download-ggml-model.sh small.en
WORKDIR /firmware

RUN mv /firmware/dependencies/librealsense2.so /usr/local/lib/python3.14/site-packages/librealsense2.so
RUN mv /firmware/dependencies/pyrealsense2.cpython-314-aarch64-linux-gnu.so /usr/local/lib/python3.14/site-packages/pyrealsense2.cpython-39-aarch64-linux-gnu.so

COPY media /firmware/media
COPY src /firmware/src

COPY .aws /root/.aws

WORKDIR  /firmware/src
